spring.profiles.active=dev

#JWT SECRET FOR DEV ONLY
application.security.jwt.expiration=900000

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.main.allow-bean-definition-overriding=true

